name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: version check
      run: | 
        mvn -v
        java -version
        ls -lrth
    
    - name: validate
      run: mvn validate
      
    - name: compile
      run: mvn compile

    - name: test
      run: mvn test

    - name: clean
      run: mvn clean
    
    - name: package
      run: mvn package

    - name: execute
      run: java -cp target/exittest-1.0-SNAPSHOT.jar com.sada.leap.App

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: target/exittest-1.0-SNAPSHOT.jar
